name: Build Android APK

on:
push:
branches: [ "main", "master" ]

jobs:
build:
runs-on: ubuntu-latest

steps:
- name: Checkout Code
  uses: actions/checkout@v4

- name: Setup Java 17
  uses: actions/setup-java@v4
  with:
    distribution: 'temurin'
    java-version: '17'

- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: '20'

- name: Install Apache Cordova
  run: npm install -g cordova

- name: Build APK Offline & Auto Version
  run: |
    cordova create android_app com.ianvex.gametk "Game TK NAFIL"
    
    # Mengubah versi di mesin Android secara otomatis berdasarkan jumlah update di GitHub
    sed -i "s/version=\"1.0.0\"/version=\"1.0.${{ github.run_number }}\" android-versionCode=\"${{ github.run_number }}\"/g" android_app/config.xml
    
    rm -rf android_app/www/*
    cp -r www/* android_app/www/
    
    # Mengubah teks Versi di layar Menu secara otomatis
    sed -i "s/Versi 1.0.0/Versi 1.0.${{ github.run_number }}/g" android_app/www/index.html
    
    cd android_app
    cordova platform add android
    cordova build android

- name: Upload Hasil APK
  uses: actions/upload-artifact@v4
  with:
    name: Game-TK-NAFIL-Update-${{ github.run_number }}
    path: android_app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
